pnc_node:
  ros__parameters:
    lattice_planner:
      limits:
        max_v: 35.0
        min_v: -0.1
        max_acc: 3.0
        min_acc: -5.0
        max_jerk: 4.0
        max_lat_offset: 3.5
        target_speed: 5.0
        planning_time: 3.0
      weights:
        w_lat: 1.0
        w_lon: 10.0
        w_offset: 2.0
        w_speed: 1.0
    use_mock_routing: false
    planning_failure_fallback_decel: -3.0